string model_id

# Parameters for the state space 
motion_planning_msgs/WorkspaceParameters workspace_parameters

# Starting state updates. If certain joints should be considered
# at positions other than the current ones, these positions should
# be set here
motion_planning_msgs/RobotState start_state

# The joint names, in the same order as the values in the state
string[] joint_names

# A list of hint states, each with the dimension of the requested model.
motion_planning_msgs/RobotState[] init_states

# The input constraints, to be converted to a set of joint constraints
motion_planning_msgs/Constraints constraints

# The maximum amount of time the search is to be run for
float64 allowed_time

---

# The set of joint constraints that correspond to the pose constraint
motion_planning_msgs/JointConstraint[] joint_constraints
