# A service call to get the joints in a particular joint group.
# A group is a collection of joints (e.g. right_arm).
# The set of group names is set using a planning_groups.yaml file.
# The file defines the set of available groups and the sets of joints 
# and links available in each of them.
string group_name

---

# A vector of joint names for all the joints in the group
string[] joint_names

# Integer error code corresponding to the first check that was violated.
# The message contains both the returned error code value and a set 
# of possible error codes.
motion_planning_msgs/ArmNavigationErrorCodes error_code