# This contains any differences the user would like 
# to apply to the current planning scene.
PlanningScene planning_scene_diff

# Diff uses ordered collision operations instead of allowed_collision_matrix
arm_navigation_msgs/OrderedCollisionOperations operations
---
# This includes the current planning scene and any changes applied from the 
# diff
PlanningScene planning_scene

						   
				   
