# group_name for configuring allowed_collisions
string group_name

# Diffs from the planning scene
PlanningScene planning_scene_diff

#Diff uses ordered collision operations instead of allowed_collision_matrix
motion_planning_msgs/OrderedCollisionOperations operations
---
PlanningScene planning_scene

						   
				   
