# Checks whether the specified state is a valid state
# The input state message
motion_planning_msgs/RobotState robot_state

# Collision checks will be performed if this flag is true
bool check_collisions

# Path constraints will be checked if this flag is true
bool check_path_constraints

# Goal constraints will be checked if this flag is true
bool check_goal_constraints

# Joint limits will be checked if this flag is true
bool check_joint_limits

# OPTIONAL group name used to disable collisions for other links
string group_name

# OPTIONAL specification of regions in space where contact between links on the robot
# and the world is allowed.
motion_planning_msgs/AllowedContactSpecification[] allowed_contacts

# OPTIONAL specification of a set of path constraints imposed on the robot, 
# e.g. joint or pose constraints. These constraints will be tested only if
# check_path_constraints = true
motion_planning_msgs/Constraints path_constraints

# OPTIONAL specification of a set of goal constraints imposed on the robot, 
# e.g. joint or pose constraints. These constraints will be tested only if 
# check_goal_constraints = true
motion_planning_msgs/Constraints goal_constraints

---

# Integer error code corresponding to the first check that was violated
# The message contains both the returned error code value and a set 
# of possible error codes
motion_planning_msgs/ArmNavigationErrorCodes error_code

# Contact information
planning_environment_msgs/ContactInformation[] contacts
