# file name for writing the planning scene
string filename

# optional package name - if set filename will be appended to this
string package_name

# Diffs from the planning scene for recording purposes
PlanningScene planning_scene_diff

#Diff uses ordered collision operations instead of allowed_collision_matrix
motion_planning_msgs/OrderedCollisionOperations operations
---

